// <auto-generated />
namespace Clarity.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removelastpayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removelastpayment));
        
        string IMigrationMetadata.Id
        {
            get { return "201306150258148_removelastpayment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
